Update .travis.yml description
This adds GHC 7.8.2 and drops GHC 6.12.3 plus a few interim GHC releases from the
GHC config matrix to reduce the resource usage on Travis. (Also, keeping support
for GHC 6.12.3 is getting more and more tedious in 2014)

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,40 +1,40 @@
-# NB: don't set `language: haskell` here
-# See https://github.com/hvr/multi-ghc-travis for more information
-
 env:
- - GHCVER=6.12.3
-# - GHCVER=7.0.1  # disabled due to internal GHC failure
- - GHCVER=7.0.2
- - GHCVER=7.0.3
- - GHCVER=7.0.4
- - GHCVER=7.2.1
- - GHCVER=7.2.2
- - GHCVER=7.4.1
- - GHCVER=7.4.2
- - GHCVER=7.6.1
- - GHCVER=7.6.2
- - GHCVER=7.6.3
- - GHCVER=head
+ - GHCVER=7.0.4 CABALVER=1.16
+ # we have to use CABALVER=1.16 for GHC<7.6 as well, as there's
+ # no package for earlier cabal versions in the PPA
+ - GHCVER=7.2.2 CABALVER=1.16
+ - GHCVER=7.4.2 CABALVER=1.16
+ - GHCVER=7.6.3 CABALVER=1.16
+ - GHCVER=7.8.2 CABALVER=1.18
+ - GHCVER=head  CABALVER=1.20
 
 matrix:
   allow_failures:
-    - env: GHCVER=head
+   - env: GHCVER=head  CABALVER=1.20
 
 before_install:
- - sudo add-apt-repository -y ppa:hvr/ghc
- - sudo apt-get update
- - sudo apt-get install cabal-install-1.18 ghc-$GHCVER
- - export PATH=/opt/ghc/$GHCVER/bin:$PATH
+ - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
+ - travis_retry sudo apt-get update
+ - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
+ - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
+ - cabal --version
 
 install:
- - cabal-1.18 update
-# can't use "cabal install --only-dependencies --enable-tests" due to dep-cycle
- - cabal-1.18 install "QuickCheck >=2.4 && <2.7" "byteorder ==1.0.*" "dlist ==0.5.*" "mtl >=2.0 && <2.2" deepseq
+ - travis_retry cabal update
+ # can't use "cabal install --only-dependencies --enable-tests" due to dep-cycle
+ - cabal install "QuickCheck >=2.4 && <2.7" "byteorder ==1.0.*" "dlist ==0.5.*" "mtl >=2.0 && <2.2" deepseq
 
 script:
- - cabal-1.18 configure --enable-tests -v2
- - cabal-1.18 build
- - cabal-1.18 test
-# "cabal check" disabled due to -O2 warning
-# - cabal-1.18 check
- - cabal-1.18 sdist
+ - cabal configure --enable-tests -v2
+ - cabal build
+ - cabal test
+ - cabal sdist
+ # "cabal check" disabled due to -O2 warning
+ - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
+   cd dist/;
+   if [ -f "$SRC_TGZ" ]; then
+      cabal install "$SRC_TGZ";
+   else
+      echo "expected '$SRC_TGZ' not found";
+      exit 1;
+   fi
